# Generated by Django 3.0.4 on 2020-03-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='status',
            field=models.CharField(choices=[('active', 'Действующая'), ('not_exist', 'Не существует')], default='active', max_length=15),
        ),
    ]
