# Generated by Django 3.0.4 on 2020-03-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_auto_20200325_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='status',
            field=models.CharField(choices=[('active', 'Действующий'), ('closed', 'Закрытый')], default='active', max_length=15),
        ),
    ]
