# Generated by Django 3.0.4 on 2020-04-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_coach'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='slug',
            field=models.SlugField(default=None, max_length=250),
        ),
    ]
