# Generated by Django 3.0.4 on 2020-04-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0008_coach_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='slug',
            field=models.SlugField(max_length=250),
        ),
    ]
