# Generated by Django 3.0.4 on 2020-04-01 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0010_auto_20200401_1004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gym',
            options={'ordering': ('short_name',), 'verbose_name': 'Тренеры'},
        ),
    ]
