# Generated by Django 3.0.4 on 2020-04-16 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0013_auto_20200401_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Judoka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=25, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=25, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=25, verbose_name='Отчество')),
                ('short_name', models.CharField(max_length=25, verbose_name='Фамилия и инициалы')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('gender', models.CharField(choices=[('male', 'Муж'), ('female', 'Жен')], default='male', max_length=6, verbose_name='Пол')),
                ('rating', models.IntegerField(default=0, verbose_name='Рейтинг')),
                ('rating_points', models.IntegerField(default=0, verbose_name='Очки рейтинга')),
                ('slug', models.SlugField(max_length=250, verbose_name='Имя для ссылки')),
                ('status', models.CharField(choices=[('active', 'Тренеруется'), ('not_active', 'Не тренеруется')], default='active', max_length=10, verbose_name='Действующий спортсмен')),
                ('pay', models.CharField(choices=[('payed', 'Оплачено'), ('not_payed', 'Не оплачено')], default='not_payed', max_length=9, verbose_name='Орг. взнос')),
            ],
            options={
                'verbose_name': 'Спортсмен',
                'verbose_name_plural': 'Спортсмены',
                'ordering': ('last_name', 'first_name', 'middle_name'),
            },
        ),
        migrations.CreateModel(
            name='WeightClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование весовой категории')),
            ],
            options={
                'verbose_name': 'Весовая котегория',
                'verbose_name_plural': 'Весовые котегории',
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='coach',
            options={'ordering': ('last_name', 'first_name', 'middle_name'), 'verbose_name': 'Тренер', 'verbose_name_plural': 'Тренеры'},
        ),
        migrations.AlterModelOptions(
            name='gym',
            options={'ordering': ('short_name',), 'verbose_name': 'Спорт. зал', 'verbose_name_plural': 'Спорт. залы'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ('short_name',), 'verbose_name': 'Организация', 'verbose_name_plural': 'Организации'},
        ),
        migrations.CreateModel(
            name='WeightHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата первого выступления в данной весовой категории')),
                ('judoka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_histories', to='tournament.Judoka', verbose_name='Спортсмен')),
                ('weight_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weight_classes', to='tournament.WeightClass', verbose_name='Весовая категория')),
            ],
        ),
        migrations.AddField(
            model_name='judoka',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='judokas', to='tournament.Coach', verbose_name='Тренер'),
        ),
    ]
