# Generated by Django 3.0.4 on 2020-04-20 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0014_auto_20200416_0531'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weighthistory',
            options={'ordering': ('judoka', 'date'), 'verbose_name': 'История весовых категорий', 'verbose_name_plural': 'Истории весовых категорий'},
        ),
        migrations.AlterField(
            model_name='weighthistory',
            name='date',
            field=models.DateField(verbose_name='Дата первого выступления в данной весовой категории'),
        ),
    ]
