# Generated by Django 3.0.4 on 2020-05-07 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0015_auto_20200420_0635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Нименование соревнования')),
                ('short_name', models.CharField(max_length=100, verbose_name='Сокращенное название')),
                ('number_of_tatami', models.IntegerField(default=1, verbose_name='Количество татами')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата проведения')),
                ('slug', models.SlugField(max_length=250, verbose_name='Алиас')),
            ],
            options={
                'verbose_name': 'Турнир',
                'verbose_name_plural': 'Турниры',
                'ordering': ('-date',),
            },
        ),
        migrations.AlterField(
            model_name='coach',
            name='slug',
            field=models.SlugField(max_length=250, verbose_name='Алиас'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='slug',
            field=models.SlugField(max_length=100, verbose_name='Алиас'),
        ),
        migrations.AlterField(
            model_name='judoka',
            name='slug',
            field=models.SlugField(max_length=250, verbose_name='Алиас'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='slug',
            field=models.SlugField(max_length=100, verbose_name='Алиас'),
        ),
    ]
