# Generated by Django 3.0.4 on 2020-05-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0016_auto_20200507_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('completed', 'Завершенный'), ('during', 'В процессе')], default='during', max_length=9, verbose_name='Статус турнира'),
        ),
    ]
