# Generated by Django 3.0.4 on 2020-05-07 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0017_tournament_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='date',
            field=models.DateField(verbose_name='Дата проведения'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Наименование соревнования'),
        ),
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_points', models.IntegerField(default=0)),
                ('slug', models.SlugField(max_length=250, verbose_name='Алиас')),
                ('judoka', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournaments', to='tournament.Judoka', verbose_name='Спортсмен')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='competitors', to='tournament.Tournament', verbose_name='Турнир')),
            ],
            options={
                'verbose_name': 'Участник турнира',
                'verbose_name_plural': 'Участники турнира',
                'ordering': ('tournament', 'judoka'),
            },
        ),
    ]
