# Generated by Django 3.0.4 on 2020-05-08 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0019_auto_20200507_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tatami',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('slug', models.SlugField(max_length=250, verbose_name='Алиас')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tatamis', to='tournament.Tournament', verbose_name='Татами')),
            ],
            options={
                'verbose_name': 'Татами',
                'verbose_name_plural': 'Татами',
            },
        ),
    ]
