# Generated by Django 3.0.4 on 2020-05-08 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0020_tatami'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tatami',
            options={'ordering': ('tournament', 'number'), 'verbose_name': 'Татами', 'verbose_name_plural': 'Татами'},
        ),
        migrations.AlterUniqueTogether(
            name='tatami',
            unique_together={('tournament', 'number')},
        ),
    ]
