# Generated by Django 3.0.4 on 2020-05-08 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0021_auto_20200508_0555'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition_system', models.CharField(choices=[('olympic', 'Олимпийская'), ('round', 'Круговая'), ('mixed', 'Смешанная')], default='olympic', max_length=7, verbose_name='Система соревнований')),
                ('slug', models.SlugField(max_length=250, verbose_name='Алиас')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournament_tables', to='tournament.Tournament', verbose_name='Татами')),
                ('weight_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tournament.WeightClass', verbose_name='Весовая категория')),
            ],
            options={
                'verbose_name': 'Турнирная таблица',
                'verbose_name_plural': 'Турнирные таблицы',
                'ordering': ('tournament', 'weight_class'),
                'unique_together': {('tournament', 'weight_class')},
            },
        ),
    ]
