# Generated by Django 3.0.4 on 2020-05-08 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0023_auto_20200508_0934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournamenttablegroup',
            options={'verbose_name': 'Турнирная группа', 'verbose_name_plural': 'Турнирные группы'},
        ),
    ]
